import Head from "next/head";
import Link from "next/link";
import { FaGithub } from 'react-icons/fa';
import { HiOutlineMail } from 'react-icons/hi';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#202020] to-[#000000]">
        <div className="container flex flex-col text-center items-center justify-center gap-12 px-4 py-16 ">
          <span className="relative top-0 bottom-48 text-white text-5xl">Hi, I'am</span>
          <span className="relative bottom-12 text-8xl mb-[15px] bg-gradient-to-r from-red-500 to-blue-500 bg-clip-text text-transparent">
            C4ID3N
          </span>
          <span className="relative bottom-24 text-5xl text-white">A Front-End Development</span>
          <p className="relative bottom-20 text-white whitespace-pre-wrap max-w-[390px] mx-auto text-2xl">
            Sou um desenvolvedor Front-End que adora transformar ideias em
            interfaces atraentes e funcionais. Tenho domínio de HTML, CSS,
            TailwindCSS, JavaScript, TypeScript, Python. Estou sempre buscando aprender novas
            ferramentas e técnicas para melhorar a experiência do usuário e a
            performance do site. No meu tempo livre, gosto de assistir séries,
            jogar videogame e praticar esportes. Meu sonho é trabalhar em uma
            empresa que valorize a criatividade e a colaboração. Caso tenha
            interesse em meus serviços, entre em contato comigo.
          </p>
          
          <div className="flex space-x-10 relative bottom-10 text-3xl text-white">
            <a href="https://github.com/c4id3nSecurity" className='hover:text-[#38383d]'>
              <FaGithub />
            </a>
            <a href="mailto:leviizinho765@gmail.com?subject=Assunto do email" className='hover:text-[#38383d]'>
              <HiOutlineMail />
            </a>
          </div>

        </div>
      </main>
    </>
  );
}
